SOURCE_DIRS=("/etc" "/home/$USER/documents" "/var/log/syslog")
BACKUP_DIR="/tmp/my_backups"
LOG_FILE="/tmp/backup.log"
SNAPSHOT_FILE="/tmp/my_backups/backup.snar"
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
KEEP_DAYS=7

ENABLE_REMOTE=false
REMOTE_TARGET="user@remote-server.com:/home/user/backups/"
ADMIN_EMAIL="admin@example.com"

ENABLE_ENCRYPTION=false
ENCRYPT_PASS="YourStrongPassword"
ENABLE_NOTIFICATION=false


